# Makefile for the unconditionalize pass
ROOT=../../..

PASSNAME := unconditionalize
OBJS := unconditionalize.o 
INCLUDES += -Ielfio-2.3
LIBS += -L$(DYNINST_ROOT)/../install/lib -ldwarf -lelf

include ../Makefile.inc
